<a href="https://colab.research.google.com/github/pikey-msc/PythonBasico/blob/master/Numpy_Insum_e_Indices_High_Performance_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#@title Imports { display-mode: "form" }
from __future__ import print_function
from __future__ import division
from __future__ import absolute_import

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

try:
  tf.enable_eager_execution()
  print('Eager execution enabled')
except ValueError:
  print('Already running in Eager mode')

tfe = tf.contrib.eager
  

Already running in Eager mode


In [1]:
import numpy as np

``numpy.einsum(subscripts, *operands, out=None, dtype=None, order='K', casting='safe', optimize=False)``

Evalúa el convenio de suma de Einstein, notación de Einstein o notación indexada a la convención utilizada para abreviar la escritura de sumatorios, en el que se suprime el símbolo de sumatorio representado con la letra griega sigma -

Usando el convenio de suma de Einstein, varias vectores multidimensionales, operaciones de arreglos de álgebra lineal puede ser representada de una manera simple.
En modo implícito einsumo calcula estos valores.

De modo explícito, einsum provee una flexibilidad más amplia para calcular otras operaciones con arreglos que puede no ser considerada una operación de suma de Einstein, por deshabilitar, o forzar la suma sobre índices específicos.


Parameteros\
``subscripts:str``\
Especifica los índices para la suma separados por una lista. Una suma clásica de Einstein se calcula a menos que se especifique el indicador `->` es incluído tanto como las etiquetas de manera precisa.

`operands:list of array_like`\
Se ingresan los arreglos para la operación.

`out: ndarray, optional`
Si se provee, el cálculo se hace en este arreglo.


`dtype:{data-type, None}, optional`\
Si se provee, forza al cálculo para usar los datos especificados. Se tiene que agregar  un parámetro de "casting" para la conversión.

`order: {‘C’, ‘F’, ‘A’, ‘K’}, optional`\
Controla el layout de la memoria de salida. ‘C’ significa que puede ser C contiguo. ‘F’ significa que puede ser Fortran contiguo, ‘A’ significa que todos los insumos debe de ser 'F'. ‘K’ significa que debe ser lo más cercano posible hacia el layout, incluyendo permutació arbitraria de ejes. El Default es ‘K’.

`casting{‘no’, ‘equiv’, ‘safe’, ‘same_kind’, ‘unsafe’}, optional`\
Controla qué tipo de conversión debe ocurrir. No se recomienda cambiarlo a 'unsafe'.

‘no’ significa que las variables no deben ser convertidas a otro formato.

‘equiv’ significa que solo cambios del byte-order están permitidas.

‘safe’ significa que solo las conversiones que pueden preservar valores están permitidas.

‘same_kind’ significa que solo conversiones safe casts or casts de untipo como float64, float32 son permitidas.

‘unsafe’ significa que cualquier conversión de datos puede ser realizada. 

El Default es ‘safe’.

`optimize:{False, True, ‘greedy’, ‘optimal’}, optional`\
Controla si la intermediación en la optimización puede ocurrir, ninguna optimización ocurrirá si es False y True utilizará el algoritmo 'greedy'.
También acepta una lista de contracción explícita de la función np.einsum_path. El Default es False.

Ejemplos:

In [3]:
a = np.arange(25).reshape(5,5)
b = np.arange(5)
c = np.arange(6).reshape(2,3)
print(a)
b


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([0, 1, 2, 3, 4])

Traza de una matriz

In [5]:
print(np.einsum('ii', a))

print(np.einsum(a, [0,0]))

print(np.trace(a))


60
60
60


Extrae la diagonal

In [6]:
print(np.einsum('ii->i', a))

print(np.einsum(a, [0,0], [0]))

print(np.diag(a))


[ 0  6 12 18 24]
[ 0  6 12 18 24]
[ 0  6 12 18 24]


Suma sobre un eje

In [7]:
print(np.einsum('ij->i', a))

print(np.einsum(a, [0,1], [0]))

np.sum(a, axis=1)


[ 10  35  60  85 110]
[ 10  35  60  85 110]


array([ 10,  35,  60,  85, 110])

Para dimensiones grandes sumando un solo eje se puede hacer con ellipsis:


In [8]:
print(np.einsum('...j->...', a))


print(np.einsum(a, [Ellipsis,1], [Ellipsis]))


[ 10  35  60  85 110]
[ 10  35  60  85 110]


Calcula una matriz transpuesta o reordena cualquier eje:

In [9]:

print(np.einsum('ji', c))

print(np.einsum('ij->ji', c))

print(np.einsum(c, [1,0]))

np.transpose(c)


[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


array([[0, 3],
       [1, 4],
       [2, 5]])

Producto interno de vectores:


In [10]:

print(np.einsum('i,i', b, b))

print(np.einsum(b, [0], b, [0]))

np.inner(b,b)


30
30


30

Multiplicación de matrices:


In [11]:

print(np.einsum('ij,j', a, b))

print(np.einsum(a, [0,1], b, [1]))

print(np.dot(a, b))

np.einsum('...j,j', a, b)


[ 30  80 130 180 230]
[ 30  80 130 180 230]
[ 30  80 130 180 230]


array([ 30,  80, 130, 180, 230])


Mulplicación con escalares:

In [12]:

print(np.einsum('..., ...', 3, c))

print(np.einsum(',ij', 3, c))
print(np.einsum(3, [Ellipsis], c, [Ellipsis]))
np.multiply(3, c)


[[ 0  3  6]
 [ 9 12 15]]
[[ 0  3  6]
 [ 9 12 15]]
[[ 0  3  6]
 [ 9 12 15]]


array([[ 0,  3,  6],
       [ 9, 12, 15]])

Producto externo: (outer product)


In [13]:

print(np.einsum('i,j', np.arange(2)+1, b))

print(np.einsum(np.arange(2)+1, [0], b, [1]))
np.outer(np.arange(2)+1, b)


[[0 1 2 3 4]
 [0 2 4 6 8]]
[[0 1 2 3 4]
 [0 2 4 6 8]]


array([[0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

Contracciones de tensores:

In [ ]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
print(np.einsum('ijk,jil->kl', a, b))
print(np.einsum(a, [0,1,2], b, [1,0,3], [2,3]))
np.tensordot(a,b, axes=([1,0],[0,1]))



Writeable returned arrays :


In [ ]:

a = np.zeros((3, 3))
np.einsum('ii->i', a)[:] = 1
a


Ejemplo de uso de ellipsis:

In [14]:
a = np.arange(6).reshape((3,2))
b = np.arange(12).reshape((4,3))
print(np.einsum('ki,jk->ij', a, b))
print(np.einsum('ki,...k->i...', a, b))
np.einsum('k...,jk', a, b)


[[10 28 46 64]
 [13 40 67 94]]
[[10 28 46 64]
 [13 40 67 94]]


array([[10, 28, 46, 64],
       [13, 40, 67, 94]])

Operaciones de arreglos en cadena. Para contracciones más complicadas, se puede mejorar la velocidad usando la opción 'greedy' u 'optimal'. 
Las mejoras pueden ser significantes con arreglos muy grandes:


In [17]:
a = np.ones(64).reshape(2,4,8)
print(a)
for iteration in range(500):
    _ = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a)

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [25]:

%%timeit 
for iteration in range(500):
  hs = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, optimize='optimal')
print(hs)

262144.0
262144.0
262144.0
262144.0
1 loop, best of 3: 491 ms per loop


In [26]:
%%timeit 
for iteration in range(500):
    _ = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, optimize='greedy')

1 loop, best of 3: 179 ms per loop


In [27]:
%%timeit 
path = np.einsum_path('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, optimize='optimal')[0]
for iteration in range(500):
    _ = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, optimize=path)

10 loops, best of 3: 129 ms per loop


## Matrix Multiplication

In [ ]:
# Define matrix A
A = np.array(
  [[1.0, 3.0],
   [2.0, 1.0],
   [4.0, 2.0]]
)

# Define matrix B
B = np.array(
  [[6.0, 2.0, 1.0],
   [3.0, 4.0, 5.0]]
)

# Define vector x
x = np.array([3.0, 2.0])

print('A.shape is:', A.shape, 'B.shape is:', B.shape, 'x.shape is:', x.shape)
A

A.shape is: (3, 2) B.shape is: (2, 3) x.shape is: (2,)


array([[1., 3.],
       [2., 1.],
       [4., 2.]])

### Matrix-vector multiplication

In [ ]:
# Using numpy dot
y = A.dot(x)

print('Using dot:\t y =', y, '\t y.shape =', y.shape)

# Using einsum
y = np.einsum('ij, j', A, x)

print('Using einsum:\t y =', y, '\t y.shape =', y.shape)

# Manual version 1
y = np.array([
    A[0,0] * x[0] + A[0,1] * x[1],
    A[1,0] * x[0] + A[1,1] * x[1],
    A[2,0] * x[0] + A[2,1] * x[1],
    ])
print('Manual 1:\t y =', y, '\t y.shape =', y.shape)

# Manual version 2: 
# Matrix-vector multiplication can be thought of as a linear combination of the columns of of the matrix
y = x[0] * A[:,0]  +  x[1] * A[:, 1]

print('Manual 2:\t y =', y, '\t y.shape =', y.shape)

Using dot:	 y = [ 9.  8. 16.] 	 y.shape = (3,)
Using einsum:	 y = [ 9.  8. 16.] 	 y.shape = (3,)
Manual 1:	 y = [ 9.  8. 16.] 	 y.shape = (3,)
Manual 2:	 y = [ 9.  8. 16.] 	 y.shape = (3,)


### Matrix-matrix multiplication

In [ ]:
# Using numpy dot
C = A.dot(B)

print('Using DOT: C= \n\n', C, '\n\nC.shape =', C.shape)

# Using einsum
C = np.einsum('ik, kj', A, B)
print('\n\nUsing einsum: C= \n\n', C, '\n\nC.shape =', C.shape)

# Note, the above einsum notation is equivalent to the following
C = np.einsum('ik, kj -> ij', A, B)

# And in Tensorflow
C = tf.matmul(A, B)
print('\n\nUsing Tensorflow: C= \n\n', C, '\n\nC.shape =', C.shape)

Using DOT: C= 

 [[15. 14. 16.]
 [15.  8.  7.]
 [30. 16. 14.]] 

C.shape = (3, 3)


Using einsum: C= 

 [[15. 14. 16.]
 [15.  8.  7.]
 [30. 16. 14.]] 

C.shape = (3, 3)


Using Tensorflow: C= 

 tf.Tensor(
[[15. 14. 16.]
 [15.  8.  7.]
 [30. 16. 14.]], shape=(3, 3), dtype=float64) 

C.shape = (3, 3)


Matrix multiplication is not commutative

In [ ]:
# Matrix multiplication is not commutative:
C = B.dot(A)
print('C: \n', C)
print()
print('C.shape:', C.shape)

C: 
 [[14. 22.]
 [31. 23.]]

C.shape: (2, 2)


## Computing gradients with TensorFlow
$y = Ax$

In the code below, we use Tensorflow to calculate the following derivatives:

$\frac{dy}{dx}$ 

and 

$\frac{\partial y}{\partial A}$ 

In [ ]:
A_tensor = tfe.Variable(A)
x_tensor = tfe.Variable(x)

with tf.GradientTape() as tape:
  y = tf.einsum('ij,j', A_tensor, x_tensor)

dydx, dydA = tape.gradient(y, [x_tensor, A_tensor])

print('dy/dx =', dydx)
print()
print('dy/dA =', dydA)

dy/dx = tf.Tensor([7. 6.], shape=(2,), dtype=float64)

dy/dA = tf.Tensor(
[[3. 2.]
 [3. 2.]
 [3. 2.]], shape=(3, 2), dtype=float64)


# Neural Network Gradient Example
In the following example, we compute the output of a 1 layer neural network and the gradients with respect to its parameters. We define an example input vector and parameters, but keep the computation generic. You can change the values and shapes of x, A and b below and run the rest of the code to compute the output and gradients for your own example.

In [ ]:
x = np.array([[-1.], [0.1], [2.1]])  # X has shape (3, 1)
A = np.array([              # A has shape (2, 3)
    [ 1.1, -2.5,  0.3],
    [-2.1,  0.2, -1.1]
])  
b = np.array([[-1.0], [2.0]])      # b has shape (2)

Compute the neural network output
$\mathbf{f} = \operatorname{tanh}(A\mathbf{x} + \mathbf{b})$

In [ ]:
M, N = A.shape
z = A.dot(x) + b
f = np.tanh(z)

print('f =', f)

f = [[-0.93786303]
 [ 0.94783185]]


Compute the partial derivatives:

\begin{align}
\frac{d\mathbf{f}}{d\mathbf{z}} ; \frac{\partial\mathbf{z}}{\partial\mathbf{x}} ; \frac{\partial\mathbf{z}}{\partial\mathbf{b}} ; \frac{\partial\mathbf{z}}{\partial\mathbf{A}}
\end{align}

In [ ]:
# partial derivatives
dfdz = 1-f**2       # (derivative of tanh is 1-tanh^2)
print('df/dz =', dfdz, '\nshape:', dfdz.shape)
print()

dzdx = A
print('dz/dx =\n', dzdx, '\n\nshape:', dzdx.shape)
print()

dzdb = np.eye(M)
print('dz/db =\n', dzdb, '\n\nshape:', dzdb.shape)
print()

dzdA = np.zeros((M, M, N))  # Start with a tensor of zeros of the correct shape
for i in range(M):          # Then set the diagonal elements of dzdA
  dzdA[i,i,:] = x.T  

print('dz/dA =\n', dzdA, '\n\nshape:', dzdA.shape)



df/dz = [[0.12041293]
 [0.10161478]] 
shape: (2, 1)

dz/dx =
 [[ 1.1 -2.5  0.3]
 [-2.1  0.2 -1.1]] 

shape: (2, 3)

dz/db =
 [[1. 0.]
 [0. 1.]] 

shape: (2, 2)

dz/dA =
 [[[-1.   0.1  2.1]
  [ 0.   0.   0. ]]

 [[ 0.   0.   0. ]
  [-1.   0.1  2.1]]] 

shape: (2, 2, 3)


Finally, we compute the gradients of the neural network output $f$ with respect to the parameters $A$ and $\mathbf{b}$ and the input $\mathbf{x}$ using the chain rule:

\begin{align}
\frac{\partial \mathbf{f}}{\partial \mathbf{x}} &= \frac{d \mathbf{f}}{d \mathbf{z}} \frac{\partial \mathbf{z}}{\partial \mathbf{x}} \ ; \ 
\frac{\partial \mathbf{f}}{\partial \mathbf{b}} = \frac{d \mathbf{f}}{d \mathbf{z}} \frac{\partial \mathbf{z}}{\partial \mathbf{b}} \ ; \ 
\frac{\partial \mathbf{f}}{\partial A} = \frac{d \mathbf{f}}{d \mathbf{z}} \frac{\partial \mathbf{z}}{\partial A} 
\end{align}

In [ ]:
dfdx = np.einsum('il, lj', dfdz, dzdx)
print('df/dx =\n', dfdx, '\n\nshape:', dfdx.shape)
print()

dfdb = np.einsum('il, lj', dfdz, dzdb)
print('df/db =\n', dfdb, '\n\nshape:', dfdb.shape)
print()

dfdA = np.einsum('il, ljk', dfdz, dzdA)
print('df/dA =\n', dfdA, '\n\nshape:', dfdA.shape)

df/dx =
 [[-0.12041293 -0.27694975 -0.09633035]
 [-0.10161478 -0.233714   -0.08129183]] 

shape: (2, 3)

df/db =
 [[0.12041293 0.12041293]
 [0.10161478 0.10161478]] 

shape: (2, 2)

df/dA =
 [[[-0.12041293  0.01204129  0.25286716]
  [-0.12041293  0.01204129  0.25286716]]

 [[-0.10161478  0.01016148  0.21339105]
  [-0.10161478  0.01016148  0.21339105]]] 

shape: (2, 2, 3)
